# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'freevpn_mac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  #pod 'Sparkle'
  # Pods for freevpn_mac

  target 'freevpn_macTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'freevpn_macUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
